post http://localhost:3000/BloodBag/InsertBloodBag
Content-Type: application/json

{
        "hospital": "638e7c0f8dce3f12d68269dd",
        "bloodType" : "O" ,
        "HBV" : "1",
        "HCV" : "0",
        "HIV" : "1",
        "HTLV" : "0",
        "syphilis" : "0" ,
        "WNV" : "0",
        "TrypanosmaCruzy" : "1" ,
        "CMV" : "1",
        "Babesia" : "1" ,
        "BacterialContamination" : "0" ,
        "pending" : "1"
}