put http://localhost:3000/patient/requestBloodBag/6388e2d953324f0ab09a97c4
Content-Type: application/json

{
    "BloodType": "test232fdsfsd323",
    "Amount": 500,
    "Date": "12/22/2022",
    "Status": "pending",
    "Purpose": "problem with his legs"
}