put http://localhost:3000/patient/requestBloodBag/638a80383bb6bc64ccce1180
Content-Type: application/json

{
    "BloodType": "A",
    "Amount": 1,
    "Date": "12/22/2022",
    "Status": "pending",
    "Purpose": "problem with his legs"
}