put http://localhost:3000/patient/modifyRequest/638a80383bb6bc64ccce1180/638dfb65782f8a2457c3af82
Content-Type: application/json

{
    "BloodType": "O",
    "Amount": 1,
    "Date": "12/22/2022",
    "Status": "test new modify",
    "Purpose": "problem with his legs"
}