post http://localhost:3000/patient
Content-Type: application/json

{
"name": "ttttttttttttttttttttttttttttt",
"email": "hagrass@bue",
"PhoneNumber": "01013700990",
"Address": "ffff",
"Condition": "dasd",
"BloodType": "B+",
"hospitalId": "1",
"Request": []
}