post http://localhost:3000/patient
Content-Type: application/json

{
"name": "testObjectID",
"email": "hagrass@bue.com",
"PhoneNumber": "01013700990",
"Address": "ffff",
"Condition": "dasd",
"BloodType": "B+",
"hospitalId": "6388db94f9a15563b956ec09",
"Request": []
}