post http://localhost:3000/auth/signup
Content-Type: application/json

{
"username": "mohamed",
"password": "mohamed",
"email": "final@gmail.com",
"phoneNumber": "1234567890",
"name": "mohamed",
"role" : "Super Admin",
"hospital": "639648820872f731e6cc1395"
}