post http://localhost:3000/auth/signup
Content-Type: application/json

{
"username": "heuwhgriei",
"password": "final",
"email": "final@gmail.com",
"phoneNumber": "1234567890",
"name": "final",
"role" : "Lab Manager",
"hospital": "639247331f144dd8a1eadacb"
}