put http://localhost:3000/hospitals/6388ded989c2a3feaa5420af
Content-Type: application/json

{
    "name": "Airforce Hospital",
    "email": "airforce@gmail",
    "PhoneNumber": "010103997420",
    "Address": "5th Settelment"
}